@startuml
'https://plantuml.com/ie-diagram

skinparam linetype ortho

Entity Subscriber{
}

Entity SubscriberCategory

Entity Category{
}

Entity Article{
}

Entity ArticleCategory{
}


Subscriber ||--o{ SubscriberCategory
Category ||--o{ SubscriberCategory

Article ||--|{ ArticleCategory
Category ||--o{ ArticleCategory


@enduml
